CREATE TABLE BLOG_TAGS(
    T_ID serial,
    TAG VARCHAR(50) NOT NULL,
  PRIMARY KEY(T_ID)
);         

CREATE  TABLE BLOG_LOGIN_ATTEMPTS(
    LA_ID serial,
    IP_ADRESS VARCHAR(128) NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
  PRIMARY KEY(LA_ID)
);    
   
CREATE TABLE BLOG_POSTS_TAGS(
    BLOG_POST_ID INT NOT NULL,
    TAGS_ID INT NOT NULL
);         
        
CREATE  TABLE BLOG_POSTS(
    BLOGPOST_ID serial,
    CONTENT TEXT NOT NULL,
    SLUG VARCHAR(150) NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    UPLOADED DATE NOT NULL,
    EDITED DATE,
    HIDDEN BOOLEAN NOT NULL DEFAULT FALSE
);
